### Data Set Source
https://www.kaggle.com/datasets/shubhambathwal/flight-price-prediction

In [254]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [255]:
## Loading the dataset and displaying the first five rows
df = pd.read_csv("/Users/saicharan/Datascience/Data/Flight Price Prediction Dataset/business.csv")
df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
0,11-02-2022,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612"
1,11-02-2022,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612"
2,11-02-2022,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220"
3,11-02-2022,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450"
4,11-02-2022,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690"

In [256]:
## Displaying the last five rows of the dataset
df.tail()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
93482,31-03-2022,Vistara,UK,822,09:45,Chennai,10h 05m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"69,265"
93483,31-03-2022,Vistara,UK,826,12:30,Chennai,10h 25m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,22:55,Hyderabad,"77,105"
93484,31-03-2022,Vistara,UK,832,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"79,099"
93485,31-03-2022,Vistara,UK,828,07:00,Chennai,10h 00m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,17:00,Hyderabad,"81,585"
93486,31-03-2022,Vistara,UK,822,09:45,Chennai,10h 05m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"81,585"

In [257]:
## Get basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        93487 non-null  object
 1   airline     93487 non-null  object
 2   ch_code     93487 non-null  object
 3   num_code    93487 non-null  int64
 4   dep_time    93487 non-null  object
 5   from        93487 non-null  object
 6   time_taken  93487 non-null  object
 7   stop        93487 non-null  object
 8   arr_time    93487 non-null  object
 9   to          93487 non-null  object
 10  price       93487 non-null  object
dtypes: int64(1), object(10)
memory usage: 7.8+ MB

In [258]:
## Get statistical summary of the dataset
df.describe()

           num_code
count  93487.000000
mean     780.056147
std      147.616038
min      401.000000
25%      706.000000
50%      820.000000
75%      874.000000
max      996.000000

In [259]:
df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
0,11-02-2022,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612"
1,11-02-2022,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612"
2,11-02-2022,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220"
3,11-02-2022,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450"
4,11-02-2022,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690"

### Date

In [260]:
## Feature Engineering and Data Preprocessing
# (This section would include handling missing values, encoding categorical variables, feature scaling, etc.)
# parse original 'date' (format DD-MM-YYYY) and extract day, month, year


# Step 2: Split and safely convert to int
df['Date'] = pd.to_numeric(df['date'].str.split('-').str[0], errors='coerce').astype('Int64')
df['Month'] = pd.to_numeric(df['date'].str.split('-').str[1], errors='coerce').astype('Int64')
df['Year'] = pd.to_numeric(df['date'].str.split('-').str[2], errors='coerce').astype('Int64')

In [261]:
df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,Date,Month,Year
0,11-02-2022,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612",11,2,2022
1,11-02-2022,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612",11,2,2022
2,11-02-2022,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",11,2,2022
3,11-02-2022,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",11,2,2022
4,11-02-2022,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",11,2,2022

In [262]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        93487 non-null  object
 1   airline     93487 non-null  object
 2   ch_code     93487 non-null  object
 3   num_code    93487 non-null  int64
 4   dep_time    93487 non-null  object
 5   from        93487 non-null  object
 6   time_taken  93487 non-null  object
 7   stop        93487 non-null  object
 8   arr_time    93487 non-null  object
 9   to          93487 non-null  object
 10  price       93487 non-null  object
 11  Date        93487 non-null  Int64
 12  Month       93487 non-null  Int64
 13  Year        93487 non-null  Int64
dtypes: Int64(3), int64(1), object(10)
memory usage: 10.3+ MB

In [263]:
## Drop Date Column because we have extracted Day, Month, Year
df.drop(columns=['date'], inplace=True)
## df.drop('Date', axis=1, inplace=True)    # If you want to drop the 'Date' column instead

In [264]:
df.head()

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,Date,Month,Year
0,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612",11,2,2022
1,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612",11,2,2022
2,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",11,2,2022
3,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",11,2,2022
4,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",11,2,2022

### Arrival Time

In [265]:
df['Arrival_Hour'] = df['arr_time'].str.split(':').str[0].astype(int)
df['Arrival_Minute'] = df['arr_time'].str.split(':').str[1].astype(int)

In [266]:
## Drop the original arrival time column because we have extracted hour and minute
df.drop(columns=['arr_time'], inplace=True)

In [267]:
df.head(2)

,airline,ch_code,num_code,dep_time,from,time_taken,stop,to,price,Date,Month,Year,Arrival_Hour,Arrival_Minute
0,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,Mumbai,"25,612",11,2,2022,20,0
1,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,Mumbai,"25,612",11,2,2022,21,15

In [268]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   airline         93487 non-null  object
 1   ch_code         93487 non-null  object
 2   num_code        93487 non-null  int64
 3   dep_time        93487 non-null  object
 4   from            93487 non-null  object
 5   time_taken      93487 non-null  object
 6   stop            93487 non-null  object
 7   to              93487 non-null  object
 8   price           93487 non-null  object
 9   Date            93487 non-null  Int64
 10  Month           93487 non-null  Int64
 11  Year            93487 non-null  Int64
 12  Arrival_Hour    93487 non-null  int64
 13  Arrival_Minute  93487 non-null  int64
dtypes: Int64(3), int64(3), object(8)
memory usage: 10.3+ MB

### Depature Time

In [269]:
df['Departure_Hour'] = df['dep_time'].str.split(':').str[0].astype(int)
df['Departure_Minute'] = df['dep_time'].str.split(':').str[1].astype(int)

In [270]:
## Drop the original Departure time column because we have extracted hour and minute
df.drop(columns=['dep_time'], inplace=True)

In [271]:
df.head(2)

,airline,ch_code,num_code,from,time_taken,stop,to,price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Departure_Hour,Departure_Minute
0,Air India,AI,868,Delhi,02h 00m,non-stop,Mumbai,"25,612",11,2,2022,20,0,18,0
1,Air India,AI,624,Delhi,02h 15m,non-stop,Mumbai,"25,612",11,2,2022,21,15,19,0

In [272]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   airline           93487 non-null  object
 1   ch_code           93487 non-null  object
 2   num_code          93487 non-null  int64
 3   from              93487 non-null  object
 4   time_taken        93487 non-null  object
 5   stop              93487 non-null  object
 6   to                93487 non-null  object
 7   price             93487 non-null  object
 8   Date              93487 non-null  Int64
 9   Month             93487 non-null  Int64
 10  Year              93487 non-null  Int64
 11  Arrival_Hour      93487 non-null  int64
 12  Arrival_Minute    93487 non-null  int64
 13  Departure_Hour    93487 non-null  int64
 14  Departure_Minute  93487 non-null  int64
dtypes: Int64(3), int64(5), object(7)
memory usage: 11.0+ MB

### Cleaning null values in column stop

In [273]:
df['stop'].unique()

array(['non-stop ',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IDR\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXU\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Chennai\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Lucknow\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia STV\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Hyderabad\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GAY\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '2+-stop',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Guwahati\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GAU\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia VTZ\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia NDC\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXE\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Raipur\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia PAT\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia RPR\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Patna\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Kolkata\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia HYD\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Delhi\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Bhubaneswar\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia BBI\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Surat\n\t\t\t\t\t\t\t\t\t\t\t\t'],
      dtype=object)

In [274]:
df[df['stop'].isnull()]            ## There is no null values in stop column

Empty DataFrame
Columns: [airline, ch_code, num_code, from, time_taken, stop, to, price, Date, Month, Year, Arrival_Hour, Arrival_Minute, Departure_Hour, Departure_Minute]
Index: []

In [275]:
df['stop'].mode()

0    1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...
Name: stop, dtype: object

In [276]:
df.head()

,airline,ch_code,num_code,from,time_taken,stop,to,price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Departure_Hour,Departure_Minute
0,Air India,AI,868,Delhi,02h 00m,non-stop,Mumbai,"25,612",11,2,2022,20,0,18,0
1,Air India,AI,624,Delhi,02h 15m,non-stop,Mumbai,"25,612",11,2,2022,21,15,19,0
2,Air India,AI,531,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,Mumbai,"42,220",11,2,2022,20,45,20,0
3,Air India,AI,839,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,Mumbai,"44,450",11,2,2022,23,55,21,25
4,Air India,AI,544,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,Mumbai,"46,690",11,2,2022,23,55,17,15

### Time Taken

In [277]:
df['hours'] = (df['time_taken'].str.split(' ').str[0].str.replace('h', '', regex=False).astype(str))
df['minutes'] = (df['time_taken'].str.split(' ').str[-1].str.replace('m', '', regex=False).astype(str))

In [278]:
df.head(2)

,airline,ch_code,num_code,from,time_taken,stop,to,price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Departure_Hour,Departure_Minute,hours,minutes
0,Air India,AI,868,Delhi,02h 00m,non-stop,Mumbai,"25,612",11,2,2022,20,0,18,0,02,00
1,Air India,AI,624,Delhi,02h 15m,non-stop,Mumbai,"25,612",11,2,2022,21,15,19,0,02,15

In [279]:
df['airline'].unique()

array(['Air India', 'Vistara'], dtype=object)

In [280]:
df['from'].unique()

array(['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai'],
      dtype=object)

### One Hot Encoder Data Preprocessing Technique

In [281]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [282]:
encoder.fit_transform(df[['airline','from','to']])   ## Sparse Matrix Output

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 280461 stored elements and shape (93487, 14)>

In [283]:
encoder.fit_transform(df[['airline','from','to']]).toarray()

array([[1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.]], shape=(93487, 14))

In [284]:
encoded_df = pd.DataFrame(
    encoder.transform(df[['airline', 'from', 'to']]).toarray(),
    columns=encoder.get_feature_names_out(['airline', 'from', 'to'])
)

In [285]:
# Reset index so both have same index alignment
encoded_df.index = df.index

In [286]:
# Drop original categorical columns
df = df.drop(['airline', 'from', 'to'], axis=1)

In [287]:
# Merge encoded columns with the original DataFrame
X_final = pd.concat(
    [df.drop(columns=['airline', 'from', 'to', 'price'], errors='ignore'), encoded_df],
    axis=1
)

In [288]:
df.head()

,ch_code,num_code,time_taken,stop,price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Departure_Hour,Departure_Minute,hours,minutes
0,AI,868,02h 00m,non-stop,"25,612",11,2,2022,20,0,18,0,02,00
1,AI,624,02h 15m,non-stop,"25,612",11,2,2022,21,15,19,0,02,15
2,AI,531,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,"42,220",11,2,2022,20,45,20,0,24,45
3,AI,839,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,"44,450",11,2,2022,23,55,21,25,26,30
4,AI,544,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,"46,690",11,2,2022,23,55,17,15,06,40