### what is  Encoding 🤔

**When you’ve got categorical data (like colors, gender, city names, etc.), machines can’t handle words directly — they only understand numbers.So we have to encode those categories into numerical form.**

### Nominal/Label Encoding
**Nominal encoding is the process of assigning a unique numerical value to each category in a categorical feature.**
| Color |                                   
| :---: |
|  Red  |
|  Blue |
| Green |
|  Red  |
| Green |


| Color | Encoded_Value |
| :---: | :-----------: |
|  Red  |       1       |
|  Blue |       2       |
| Green |       3       |
|  Red  |       1       |
| Green |       3       |


### One Hot Encoding
**One-hot encoding converts each category into a binary vector, creating separate columns for every unique category.**
| Color | Red | Blue | Green |
| :---: | :-: | :--: | :---: |
|  Red  |  1  |   0  |   0   |
|  Blue |  0  |   1  |   0   |
| Green |  0  |   0  |   1   |
|  Red  |  1  |   0  |   0   |
| Green |  0  |   0  |   1   |

### Sparse Matrix
**A sparse matrix is a large matrix where most elements are zeros, so instead of storing every value, only the non-zero elements and their positions are kept. This saves a ton of memory and computation time, especially when dealing with data that naturally has many zeros — like one-hot encoded features, text data (bag of words or TF-IDF), or graph connections. In contrast, a dense matrix stores every element, which is only efficient when most values are non-zero Sparse matrices make big data processing practical and fast.**

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
# Create a sample DataFrame
data = {'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red']}
df = pd.DataFrame(data)

In [3]:
df.head()

   Color
0    Red
1   Blue
2  Green
3   Blue
4    Red

In [6]:
## Create an instance of OneHotEncoder
encoder = OneHotEncoder()

In [9]:
# Perform fit and transform
encoded=encoder.fit_transform(df[['Color']]).toarray()

In [11]:
import pandas as pd
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['Color']))
encoder_df

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         1.0          0.0        0.0
4         0.0          0.0        1.0

In [13]:
encoder.transform([['Red']]).toarray()

/Users/saicharan/Datascience/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1.]])

In [14]:
pd.concat([df, encoder_df], axis = 1)

   Color  Color_Blue  Color_Green  Color_Red
0    Red         0.0          0.0        1.0
1   Blue         1.0          0.0        0.0
2  Green         0.0          1.0        0.0
3   Blue         1.0          0.0        0.0
4    Red         0.0          0.0        1.0

In [16]:
df.head()

   Color
0    Red
1   Blue
2  Green
3   Blue
4    Red

In [26]:
from sklearn.preprocessing import LabelEncoder

lbl_encoder = LabelEncoder()
lbl_encoder.fit_transform(df[['Color']])

/Users/saicharan/Datascience/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 0, 2])

In [28]:

lbl_encoder.transform([['Red'], ['Green'], ['Blue']])

/Users/saicharan/Datascience/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2, 1, 0])

### Ordinal Encoding
**Ordinal encoding is a data preprocessing technique used to convert categorical variables (text labels) into numerical values, but unlike regular label encoding, it’s specifically designed for ordered categories — categories that have a meaningful ranking or hierarchy.**

### Example
| Satisfaction     | Encoded |
| ---------------- | ------- |
| Very Unsatisfied | 1       |
| Unsatisfied      | 2       |
| Neutral          | 3       |
| Satisfied        | 4       |
| Very Satisfied   | 5       |

**Now, the algorithm knows that 5 > 4 > 3 > 2 > 1, and that the difference between “Very Unsatisfied” and “Satisfied” is meaningful in the context of order, even if not strictly linear.**

In [29]:
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({
    'Satisfaction' : ['Very Unsatisfied', 'Unsatisfied', 'Neutral', 'Satisfied', 'Very Satisfied']
})

In [30]:
df

       Satisfaction
0  Very Unsatisfied
1       Unsatisfied
2           Neutral
3         Satisfied
4    Very Satisfied

In [33]:
## Create an instance of OneHotEncoder
encoder = OrdinalEncoder(categories=[['Very Unsatisfied', 'Unsatisfied', 'Neutral', 'Satisfied', 'Very Satisfied']])
# Perform fit and transform
encoded = encoder.fit_transform(df[['Satisfaction']])
encoded

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.]])

In [34]:
encoder.transform([['Very Satisfied']])

/Users/saicharan/Datascience/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[4.]])