In [96]:
import pandas as pd

### Introduction To Pandas

In [97]:
df = pd.DataFrame([[1,2,3],
                   [4,5,6],
                   [7,8,9]], columns=['A','B','C'],index=['X','Y','Z'])
df.head()

   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [98]:
df.head(2)

   A  B  C
X  1  2  3
Y  4  5  6

In [99]:
df.tail(2)

   A  B  C
Y  4  5  6
Z  7  8  9

In [100]:
df.index

Index(['X', 'Y', 'Z'], dtype='object')

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, X to Z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [102]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [103]:
df['A'].unique()

array([1, 4, 7])

In [104]:
df.shape

(3, 3)

In [105]:
df.shape

(3, 3)

In [106]:
df.size

9

### Loading in dataframes from files

In [107]:
result = pd.read_parquet('./data/results.parquet', engine='fastparquet')

In [108]:
olympics_data = pd.read_excel('./data/olympics-data.xlsx', sheet_name='results')

In [109]:
bios_data = pd.read_csv('./data/bios.csv')

In [110]:
coffee_data = pd.read_csv('./data/coffee.csv')

### Accessing data with pandas

In [111]:
coffee_data

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [112]:
display(coffee_data)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [113]:
coffee_data.sample(10)

          Day Coffee Type  Units Sold
13     Sunday       Latte          35
3     Tuesday       Latte          20
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
0      Monday    Espresso          25
1      Monday       Latte          15
10   Saturday    Espresso          45
12     Sunday    Espresso          45
9      Friday       Latte          35
11   Saturday       Latte          35

In [114]:
coffee_data

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [115]:
coffee_data.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [116]:
coffee_data.loc[0:4]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [117]:
coffee_data.loc[4:, ['Day','Units Sold']]

          Day  Units Sold
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [118]:
#coffee_data.index = coffee_data['Day']     # Setting index to Day column

In [119]:
#coffee_data.loc['Monday':'Wednesday','Units Sold']

In [120]:
#coffee_data.iloc[#rows , #columns] # Only can access by index values

In [121]:
coffee_data

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [122]:
coffee_data.iat[0,0]     # Access a single value for a row/column pair by integer position

'Monday'

In [123]:
coffee_data["Day"]

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [125]:
coffee_data.sort_values(by='Units Sold')

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [127]:
coffee_data.sort_values(by='Units Sold',ascending=False)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [128]:
coffee_data.sort_values(by=['Units Sold','Coffee Type'],ascending=False)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
2     Tuesday    Espresso          30
5   Wednesday       Latte          25
0      Monday    Espresso          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [129]:
coffee_data.sort_values(by=['Units Sold','Coffee Type'],ascending=[0,1])     # o for desceding Units Sold and 1 for Ascending Coffee Type

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [131]:
# Iterating Through Rows 
for index, row in coffee_data.iterrows():
    print(index, row['Day'], row["Units Sold"])
    print("\n\n")

0 Monday 25



1 Monday 15



2 Tuesday 30



3 Tuesday 20



4 Wednesday 35



5 Wednesday 25



6 Thursday 40



7 Thursday 30



8 Friday 45



9 Friday 35



10 Saturday 45



11 Saturday 35



12 Sunday 45



13 Sunday 35

### Filtering Data

In [132]:
bios_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25