### Pandas Dataframe and series
**Series:A Pandas Series is a one-dimensional labeled array that can hold data of any type (integer, string, float, etc.) with an associated index.**

**Data Frame: A Pandas DataFrame is a two-dimensional, tabular data structure with labeled rows and columns, where each column is essentially a Series.**

In [1]:
import pandas as pd

In [2]:
# Series
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series of Numbers \n",series)
print(type(series))

Series of Numbers
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [3]:
# Create a series with dictionary
data = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)
print(type(series_dict))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [5]:
# Data set Imported from kaggle website
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shreyanshverma27/online-sales-dataset-popular-marketplace-data")

print("Path to dataset files:", path)

/Users/saicharan/Datascience/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /Users/saicharan/.cache/kagglehub/datasets/shreyanshverma27/online-sales-dataset-popular-marketplace-data/versions/1

In [6]:
# DataFrame
# Create a dataframe from dictionary of list
data = {
    'Name':['Krish','bharath','ismail'],
    'Age': [20,24,28],
    'city':["bangalore",'Amaravati','Telangana']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       city
0    Krish   20  bangalore
1  bharath   24  Amaravati
2   ismail   28  Telangana
<class 'pandas.core.frame.DataFrame'>

In [7]:
# create a data frame from list of dictionaries
data = [
    {'Name':'Krish','Age':20,'city':'vizag'},
    {'Name':'bharath','Age':23,'city':'Amaravati'},
    {'Name':'Krishna','Age':28,'city':'Guntur'},
]
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       city
0    Krish   20      vizag
1  bharath   23  Amaravati
2  Krishna   28     Guntur
<class 'pandas.core.frame.DataFrame'>

In [8]:
# Reading A DataSet
data_set = pd.read_csv('./data/Sales_Data.csv')
data_set

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [9]:
data_set.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [10]:
data_set.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [11]:
# ACCESSING DATA FROM DATA FRAME
df

      Name  Age       city
0    Krish   20      vizag
1  bharath   23  Amaravati
2  Krishna   28     Guntur

In [12]:
df['Name']

0      Krish
1    bharath
2    Krishna
Name: Name, dtype: object

In [13]:
print(type(df['Name']))

<class 'pandas.core.series.Series'>

In [14]:
# Accessing by Rows
df.loc[0][2]

/var/folders/xb/vyz_qx5s77jg7x5dhbnpnwx00000gn/T/ipykernel_90254/2120500375.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][2]

'vizag'

In [15]:
print(type(df.loc[0]))

<class 'pandas.core.series.Series'>

In [16]:
# Accessing by Columns
df.iloc[0]

Name    Krish
Age        20
city    vizag
Name: 0, dtype: object

In [17]:
print(type(df.iloc[0]))

<class 'pandas.core.series.Series'>

In [18]:
# Accessing Specific Element
df

      Name  Age       city
0    Krish   20      vizag
1  bharath   23  Amaravati
2  Krishna   28     Guntur

In [19]:
df.at[1,'city']

'Amaravati'

In [20]:
# Accessing Specific element at iat (INDEXING)
df.iat[2,2]

'Guntur'

### Data manupulation

In [21]:
df

      Name  Age       city
0    Krish   20      vizag
1  bharath   23  Amaravati
2  Krishna   28     Guntur

In [22]:
df['salary'] = [100000,200000,300000]

In [23]:
df

      Name  Age       city  salary
0    Krish   20      vizag  100000
1  bharath   23  Amaravati  200000
2  Krishna   28     Guntur  300000

In [24]:
# Remove a Column
df.drop('salary',axis = 1,inplace = True)  # DEFAULT = 0 MEANS ROW, AXIS = 1 MEANS COLUMN AND INPLACE = TRUE MEANS PERMANENTLY REMOVES THE COLUMN

In [25]:
df

      Name  Age       city
0    Krish   20      vizag
1  bharath   23  Amaravati
2  Krishna   28     Guntur

In [26]:
# Add age column increased by number
df['Age'] = df['Age'] + 1
df

      Name  Age       city
0    Krish   21      vizag
1  bharath   24  Amaravati
2  Krishna   29     Guntur

In [27]:
df.drop(0,inplace=True)

In [28]:
df

      Name  Age       city
1  bharath   24  Amaravati
2  Krishna   29     Guntur

In [29]:
data_set

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [30]:
print("Data Types of Data set: \n",data_set.dtypes)

Data Types of Data set:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In [31]:
print("Statistical Summary of Dataset: \n",data_set.describe())

Statistical Summary of Dataset:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [32]:
data_set.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

### Definition: Data Manipulation and Analysis with Python

**Data manipulation and analysis with Python means using Python libraries (like pandas, NumPy, etc.) to clean, transform, organize, and study data so we can extract useful information, find patterns, or gain insights.**

**Data Manipulation = adjusting the raw data → cleaning, filtering, sorting, adding new columns, deleting bad data, handling missing values**

**Data Analysis = interpreting that cleaned data → calculating stats, finding trends, summarizing, visualizing, making decisions**

In [33]:
data_set.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [34]:
data_set.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [35]:
data_set.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [36]:
data_set.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In [37]:
# Handling Missing Values
data_set.isnull().any(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
235    False
236    False
237    False
238    False
239    False
Length: 240, dtype: bool

In [38]:
data_set.isnull().any()

Transaction ID      False
Date                False
Product Category    False
Product Name        False
Units Sold          False
Unit Price          False
Total Revenue       False
Region              False
Payment Method      False
dtype: bool

In [39]:
data_set.isnull().sum()

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          0
Total Revenue       0
Region              0
Payment Method      0
dtype: int64

In [40]:
# Filling missing values with mean of column
# Filling Missing Values with means of column
data_set['Unit_Price'] = data_set['Unit Price'].fillna(data_set['Unit Price'].mean())
data_set

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Unit_Price
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,999.99
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,69.99
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,15.99
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99
...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal,159.99
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card,90.00
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,10.99
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal,55.00
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,29.99

In [41]:
# Renaming Columns
Renamed_data=data_set.rename(columns={'Date':'Oreder_Date'})
Renamed_data.head(5)

,Transaction ID,Oreder_Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Unit_Price
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,999.99
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,69.99
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,15.99
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99

In [42]:
# Change Datatypes
data_set['Units Sold_New'] = data_set['Units Sold'].astype('float')
data_set.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Unit_Price,Units Sold_New
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,999.99,2.0
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,1.0
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,69.99,3.0
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,15.99,4.0
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,1.0

In [43]:
data_set['Units Sold_New'] = data_set['Units Sold'].astype('int')
data_set.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Unit_Price,Units Sold_New
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,999.99,2
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,1
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,69.99,3
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,15.99,4
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,1

In [44]:
# Change Datatypes and apply function
data_set['Units Sold_New'] = data_set['Units Sold'].apply(lambda x: x * 2)
data_set.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Unit_Price,Units Sold_New
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,999.99,4
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,2
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,69.99,6
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,15.99,8
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,2

In [45]:
# Data Aggregating and Grouping
data_set.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Unit_Price,Units Sold_New
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,999.99,4
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,2
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,69.99,6
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,15.99,8
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,2

In [46]:
Grouped_data = data_set.groupby('Product Name')['Unit Price'].mean().reset_index()
print(Grouped_data)

                                          Product Name  Unit Price
0                                1984 by George Orwell       19.99
1                              Adidas 3-Stripes Shorts       29.99
2                         Adidas Essential Track Pants       44.99
3                       Adidas FIFA World Cup Football       29.99
4                  Adidas Originals Superstar Sneakers       79.99
..                                                 ...         ...
227           Yeti Tundra Haul Portable Wheeled Cooler      399.99
228  Youth to the People Superfood Antioxidant Clea...       36.00
229                                  Zara Summer Dress       59.99
230                                      iPhone 14 Pro      999.99
231                               iRobot Braava Jet M6      449.99

[232 rows x 2 columns]

In [47]:
grouped_sum=data_set.groupby(['Product Category','Region'])['Unit Price'].sum()
print(grouped_sum)

Product Category  Region
Beauty Products   Europe            2464.92
Books             North America      646.12
Clothing          Asia              2701.46
Electronics       North America    27663.66
Home Appliances   Europe           12807.42
Sports            Asia             10451.36
Name: Unit Price, dtype: float64

In [48]:
data_set.groupby(['Product Category','Region'])['Unit Price'].mean()

Product Category  Region
Beauty Products   Europe            61.6230
Books             North America     16.1530
Clothing          Asia              67.5365
Electronics       North America    691.5915
Home Appliances   Europe           320.1855
Sports            Asia             261.2840
Name: Unit Price, dtype: float64

In [49]:
## Aggregate Multiple Functions
Grouped_agg=data_set.groupby('Region')['Unit Price'].agg(['sum','mean','count'])
Grouped_agg

                    sum       mean  count
Region
Asia           13152.82  164.41025     80
Europe         15272.34  190.90425     80
North America  28309.78  353.87225     80

In [50]:
# Merging And Joining DataFrames
df1 = pd.DataFrame({'key':['A','B','C'],'Value1':[1,2,3]})
df2 = pd.DataFrame({'key':['A','B','D'],'Value1':[4,5,6]})

In [51]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

In [52]:
df2

  key  Value1
0   A       4
1   B       5
2   D       6

In [53]:
# Merging DataFrames on key Columns
pd.merge(df1,df2, on='key', how='inner')

  key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [54]:
pd.merge(df1,df2, on='key', how='outer')

  key  Value1_x  Value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0

In [55]:
pd.merge(df1,df2, on='key', how='left')

  key  Value1_x  Value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [56]:
pd.merge(df1,df2, on='key', how='right')

  key  Value1_x  Value1_y
0   A       1.0         4
1   B       2.0         5
2   D       NaN         6