### Pandas Dataframe and series
**Pandas:A Pandas Series is a one-dimensional labeled array that can hold data of any type (integer, string, float, etc.) with an associated index.**

**Data Frame: A Pandas DataFrame is a two-dimensional, tabular data structure with labeled rows and columns, where each column is essentially a Series.**

In [1]:
import pandas as pd

In [4]:
# Series
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series of Numbers \n",series)
print(type(series))

Series of Numbers
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [8]:
# Create a series with dictionary
data = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)
print(type(series_dict))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>

In [9]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [ ]:
# Data set Imported from kaggle website
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shreyanshverma27/online-sales-dataset-popular-marketplace-data")

print("Path to dataset files:", path)

/Users/saicharan/Datascience/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading from https://www.kaggle.com/api/v1/datasets/download/shreyanshverma27/online-sales-dataset-popular-marketplace-data?dataset_version_number=1...

100%|██████████| 6.78k/6.78k [00:00<00:00, 4.78MB/s]

Extracting files...
Path to dataset files: /Users/saicharan/.cache/kagglehub/datasets/shreyanshverma27/online-sales-dataset-popular-marketplace-data/versions/1

In [14]:
# DataFrame
# Create a dataframe from dictionary of list
data = {
    'Name':['Krish','bharath','ismail'],
    'Age': [20,24,28],
    'city':["bangalore",'Amaravati','Telangana']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       city
0    Krish   20  bangalore
1  bharath   24  Amaravati
2   ismail   28  Telangana
<class 'pandas.core.frame.DataFrame'>

In [ ]:
# create a data frame from list of dictionaries
data = [
    {'Name':'Krish','Age':20,'city':'vizag'},
    {'Name':'bharath','Age':23,'city':'Amaravati'},
    {'Name':'Krishna','Age':28,'city':'Guntur'},
]
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       city
0    Krish   20      vizag
1  bharath   23  Amaravati
2  Krishna   28     Guntur
<class 'pandas.core.frame.DataFrame'>

In [23]:
# Reading A DataSet
data_set = pd.read_csv('Sales_Data.csv')
data_set

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [24]:
data_set.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [25]:
data_set.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [26]:
# ACCESSING DATA FROM DATA FRAME
df

      Name  Age       city
0    Krish   20      vizag
1  bharath   23  Amaravati
2  Krishna   28     Guntur

In [ ]:
df['Name']

0      Krish
1    bharath
2    Krishna
Name: Name, dtype: object

In [29]:
print(type(df['Name']))

<class 'pandas.core.series.Series'>

In [43]:
# Accessing by Rows
df.loc[0][2]

/var/folders/xb/vyz_qx5s77jg7x5dhbnpnwx00000gn/T/ipykernel_59343/2120500375.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][2]

'vizag'

In [34]:
print(type(df.loc[0]))

<class 'pandas.core.series.Series'>

In [47]:
# Accessing by Columns
df.iloc[0]

Name    Krish
Age        20
city    vizag
Name: 0, dtype: object

In [35]:
print(type(df.iloc[0]))

<class 'pandas.core.series.Series'>

In [48]:
# Accessing Specific Element
df

      Name  Age       city
0    Krish   20      vizag
1  bharath   23  Amaravati
2  Krishna   28     Guntur

In [49]:
df.at[1,'city']

'Amaravati'

In [ ]:
# Accessing Specific element at iat (INDEXING)
df.iat[2,2]

'Guntur'

### Data manupulation

In [52]:
df

      Name  Age       city
0    Krish   20      vizag
1  bharath   23  Amaravati
2  Krishna   28     Guntur

In [53]:
df['salary'] = [100000,200000,300000]

In [54]:
df

      Name  Age       city  salary
0    Krish   20      vizag  100000
1  bharath   23  Amaravati  200000
2  Krishna   28     Guntur  300000

In [58]:
# Remove a Column
df.drop('salary',axis = 1,inplace = True)  # DEFAULT = 0 MEANS ROW, AXIS = 1 MEANS COLUMN AND INPLACE = TRUE MEANS PERMANENTLY REMOVES THE COLUMN

In [59]:
df

      Name  Age       city
0    Krish   20      vizag
1  bharath   23  Amaravati
2  Krishna   28     Guntur

In [61]:
# Add age column increased by number
df['Age'] = df['Age'] + 1
df

      Name  Age       city
0    Krish   21      vizag
1  bharath   24  Amaravati
2  Krishna   29     Guntur

In [62]:
df.drop(0,inplace=True)

In [63]:
df

      Name  Age       city
1  bharath   24  Amaravati
2  Krishna   29     Guntur

In [67]:
data_set

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [72]:
print("Data Types of Data set: \n",data_set.dtypes)

Data Types of Data set:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In [73]:
print("Statistical Summary of Dataset: \n",data_set.describe())

Statistical Summary of Dataset:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [75]:
data_set.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000