In [1]:
import pandas as pd

### Introduction To Pandas

In [2]:
df = pd.DataFrame([[1,2,3],
                   [4,5,6],
                   [7,8,9]], columns=['A','B','C'],index=['X','Y','Z'])
df.head()

   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [3]:
df.head(2)

   A  B  C
X  1  2  3
Y  4  5  6

In [4]:
df.tail(2)

   A  B  C
Y  4  5  6
Z  7  8  9

In [5]:
df.index

Index(['X', 'Y', 'Z'], dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, X to Z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [7]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [8]:
df['A'].unique()

array([1, 4, 7])

In [9]:
df.shape

(3, 3)

In [10]:
df.shape

(3, 3)

In [11]:
df.size

9

### Loading in dataframes from files

In [12]:
result = pd.read_parquet('./data/results.parquet', engine='fastparquet')

In [13]:
olympics_data = pd.read_excel('./data/olympics-data.xlsx', sheet_name='results')

In [107]:
bios_data = pd.read_csv('./data/bios.csv')

In [162]:
coffee_data = pd.read_csv('./data/coffee.csv')

In [112]:
nocs = pd.read_csv('./data/noc_regions.csv')

### Accessing data with pandas

In [16]:
coffee_data

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [17]:
display(coffee_data)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [18]:
coffee_data.sample(10)

          Day Coffee Type  Units Sold
2     Tuesday    Espresso          30
0      Monday    Espresso          25
6    Thursday    Espresso          40
8      Friday    Espresso          45
5   Wednesday       Latte          25
1      Monday       Latte          15
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
10   Saturday    Espresso          45

In [19]:
coffee_data

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [20]:
coffee_data.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [21]:
coffee_data.loc[0:4]

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [22]:
coffee_data.loc[4:, ['Day','Units Sold']]

          Day  Units Sold
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [23]:
#coffee_data.index = coffee_data['Day']     # Setting index to Day column

In [24]:
#coffee_data.loc['Monday':'Wednesday','Units Sold']

In [25]:
#coffee_data.iloc[#rows , #columns] # Only can access by index values

In [26]:
coffee_data

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [27]:
coffee_data.iat[0,0]     # Access a single value for a row/column pair by integer position

'Monday'

In [28]:
coffee_data["Day"]

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [29]:
coffee_data.sort_values(by='Units Sold')

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [30]:
coffee_data.sort_values(by='Units Sold',ascending=False)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [31]:
coffee_data.sort_values(by=['Units Sold','Coffee Type'],ascending=False)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
2     Tuesday    Espresso          30
5   Wednesday       Latte          25
0      Monday    Espresso          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [32]:
coffee_data.sort_values(by=['Units Sold','Coffee Type'],ascending=[0,1])     # o for desceding Units Sold and 1 for Ascending Coffee Type

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [33]:
# Iterating Through Rows 
for index, row in coffee_data.iterrows():
    print(index, row['Day'], row["Units Sold"])
    print("\n\n")

0 Monday 25



1 Monday 15



2 Tuesday 30



3 Tuesday 20



4 Wednesday 35



5 Wednesday 25



6 Thursday 40



7 Thursday 30



8 Friday 45



9 Friday 35



10 Saturday 45



11 Saturday 35



12 Sunday 45



13 Sunday 35

### Filtering Data

In [34]:
bios_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [35]:
bios_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [36]:
bios_data.loc[bios_data['height_cm'] > 215, ['name','height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [37]:
bios_data[(bios_data['height_cm'] > 215) & (bios_data['born_country'] == 'USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [38]:
bios_data[bios_data['name'].str.contains('Tyson Chandler', case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [40]:
bios_data[bios_data['born_country'].isin(['USA','FRA','GBR']) & (bios_data['name'].str.startswith("Keith"))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
14577,14674,Keith Harrison,1933-03-28,Birmingham,England,GBR,Great Britain,NaN,NaN,NaN
16166,16281,Keith Reynolds,1963-12-25,Solihull,England,GBR,Great Britain,173.0,68.0,NaN
18734,18862,Keith Sinclair,1945-06-26,Sunderland,England,GBR,Great Britain,190.0,79.0,NaN
29897,30123,Keith Langley,1961-06-03,Aldershot,England,GBR,Great Britain,173.0,70.0,NaN
34011,34275,Keith Remfry,1947-11-17,Ealing,England,GBR,Great Britain,193.0,114.0,2015-09-16
46885,47234,Keith Collin,1937-01-18,Marylebone,England,GBR,Great Britain,168.0,63.0,1991-03-06
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
55317,55712,Keith Boxell,1958-05-06,Clapham,England,GBR,Great Britain,170.0,87.0,NaN
57818,58226,Keith Peache,1947-08-10,Lewisham,England,GBR,Great Britain,180.0,98.0,NaN
61748,62202,Keith Grogono,1912-11-04,Stratford,England,GBR,Great Britain,NaN,NaN,1999-03-22
62620,63086,Keith Musto,1936-01-12,Rochford,England,GBR,Great Britain,174.0,72.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
68324,68841,Keith Angus,1943-04-05,Sheffield,England,GBR,Great Britain,170.0,59.0,NaN
68472,68989,Keith Cullen,1972-06-13,Ilford,England,GBR,Great Britain,177.0,61.0,NaN
68997,69514,Keith Stock,1957-03-18,Woolwich,England,GBR,Great Britain,176.0,73.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
95267,96037,Keith Oliver,1947-10-27,Liverpool,England,GBR,Great Britain,172.0,68.0,NaN
96452,97229,Keith Schellenberg,1929-03-13,Middlesbrough,England,GBR,Great Britain,NaN,NaN,2019-10-28
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN

### Adding and removing Columns from Dataset

In [81]:
coffee_new = coffee_data.copy()

In [82]:
coffee_new['Price'] = 4.99

In [83]:
coffee_new.head()

         Day Coffee Type  Units Sold  Price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [84]:
import numpy as np
coffee_new['new_price'] = np.where(coffee_new['Coffee Type']== "Espresso", 3.99, 5.99)
coffee_new.head()

         Day Coffee Type  Units Sold  Price  new_price
0     Monday    Espresso          25   4.99       3.99
1     Monday       Latte          15   4.99       5.99
2    Tuesday    Espresso          30   4.99       3.99
3    Tuesday       Latte          20   4.99       5.99
4  Wednesday    Espresso          35   4.99       3.99

In [85]:
coffee_new.drop(columns=['Price'], inplace=True)

In [86]:
coffee_new.head()

         Day Coffee Type  Units Sold  new_price
0     Monday    Espresso          25       3.99
1     Monday       Latte          15       5.99
2    Tuesday    Espresso          30       3.99
3    Tuesday       Latte          20       5.99
4  Wednesday    Espresso          35       3.99

In [87]:
coffee_new['Revenue'] = coffee_new['Units Sold'] * coffee_new['new_price']

In [89]:
coffee_new.head()

         Day Coffee Type  Units Sold  new_price  Revenue
0     Monday    Espresso          25       3.99    99.75
1     Monday       Latte          15       5.99    89.85
2    Tuesday    Espresso          30       3.99   119.70
3    Tuesday       Latte          20       5.99   119.80
4  Wednesday    Espresso          35       3.99   139.65

In [90]:
coffee_new.rename(columns={'new_price':'Price'}, inplace=True)

In [92]:
coffee_new.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   3.99    99.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   3.99   119.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   3.99   139.65

In [93]:
bios_new = bios_data.copy()

In [94]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [98]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])

In [99]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,2002-01-30
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,1999-09-20
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,1998-05-08
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,1899-05-19
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,1913-07-15

In [100]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year
bios_new[['name','born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [101]:
bios_new.to_csv('./data/data_bios_new.csv', index=False)

### Adding and removing files using lambda and costum functions

In [102]:
bios_data['Height Category'] = bios_data['height_cm'].apply(lambda x: 'Short' if x < 165 else('Average' if x < 185 else 'Tall'))

In [103]:
bios_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,Height Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall

In [104]:
def categorize_athlete(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'Short and Light'
    elif row['height_cm'] < 185 and row['weight_kg'] <= 80:
        return 'Average'
    else:
        return 'Large and Heavy'
bios_data['Category'] = bios_data.apply(categorize_athlete, axis=1)

In [105]:
bios_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,Height Category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Large and Heavy
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Short and Light
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Large and Heavy

### Merging and concatenating data

In [114]:
bios_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [117]:
bios_new = pd.merge(bios_data, nocs, left_on='born_country',right_on='NOC',how='left')

In [119]:
bios_new.rename(columns={'region':'born_country_full'},inplace=True)

In [120]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [122]:
bios_new[bios_new['NOC_x'] != bios_new['born_country_full']][['name','NOC_x','born_country_full']]

                       name    NOC_x born_country_full
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

In [125]:
usa = bios_new[bios_new['born_country'] == 'USA'].copy()
gbr = bios_new[bios_new['born_country'] == 'GBR'].copy()

In [126]:
usa.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_country_full,notes
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,USA,USA,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,USA,USA,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,USA,USA,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,USA,USA,NaN
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,USA,USA,NaN

In [127]:
gbr.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_country_full,notes
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN
37,38,Helen Aitchison,1881-12-06,Sunderland,England,GBR,Great Britain,NaN,NaN,1947-05-26,GBR,UK,NaN
38,39,Geraldine Beamish,1883-06-23,Forest Gate,England,GBR,Great Britain,NaN,NaN,1972-05-10,GBR,UK,NaN
39,40,Dora Boothby,1881-08-02,Finchley,England,GBR,Great Britain,NaN,NaN,1970-02-22,GBR,UK,NaN
40,41,Julie Bradbury,1967-02-12,Oxford,England,GBR,Great Britain,175.0,64.0,NaN,GBR,UK,NaN

In [131]:
concatenate_df = pd.concat([usa,gbr])

In [132]:
concatenate_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_country_full,notes
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,USA,USA,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,USA,USA,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,USA,USA,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,USA,USA,NaN
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,USA,USA,NaN

In [134]:
combined_df = pd.merge(result,bios_data, on='athlete_id', how='left')

In [136]:
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02

### Handling Null Values

In [137]:
coffee_data.loc[[0,1],'Units Sold'] = np.nan

In [140]:
coffee_data

          Day Coffee Type  Units Sold
0      Monday    Espresso         NaN
1      Monday       Latte         NaN
2     Tuesday    Espresso        30.0
3     Tuesday       Latte        20.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [141]:
coffee_data.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
dtype: int64

In [142]:
coffee_data.fillna(1000)

          Day Coffee Type  Units Sold
0      Monday    Espresso      1000.0
1      Monday       Latte      1000.0
2     Tuesday    Espresso        30.0
3     Tuesday       Latte        20.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [143]:
coffee_data.fillna(coffee_data['Units Sold'].mean())

          Day Coffee Type  Units Sold
0      Monday    Espresso        35.0
1      Monday       Latte        35.0
2     Tuesday    Espresso        30.0
3     Tuesday       Latte        20.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [148]:
coffee_data.loc[[0,1],'Units Sold'] = 15

In [149]:
coffee_data.loc[[2,3],'Units Sold'] = np.nan

In [151]:
coffee_data['Units Sold']=coffee_data['Units Sold'].interpolate()

In [152]:
coffee_data

          Day Coffee Type  Units Sold
0      Monday    Espresso   15.000000
1      Monday       Latte   15.000000
2     Tuesday    Espresso   21.666667
3     Tuesday       Latte   28.333333
4   Wednesday    Espresso   35.000000
5   Wednesday       Latte   25.000000
6    Thursday    Espresso   40.000000
7    Thursday       Latte   30.000000
8      Friday    Espresso   45.000000
9      Friday       Latte   35.000000
10   Saturday    Espresso   45.000000
11   Saturday       Latte   35.000000
12     Sunday    Espresso   45.000000
13     Sunday       Latte   35.000000

In [153]:
coffee_data.dropna()

          Day Coffee Type  Units Sold
0      Monday    Espresso   15.000000
1      Monday       Latte   15.000000
2     Tuesday    Espresso   21.666667
3     Tuesday       Latte   28.333333
4   Wednesday    Espresso   35.000000
5   Wednesday       Latte   25.000000
6    Thursday    Espresso   40.000000
7    Thursday       Latte   30.000000
8      Friday    Espresso   45.000000
9      Friday       Latte   35.000000
10   Saturday    Espresso   45.000000
11   Saturday       Latte   35.000000
12     Sunday    Espresso   45.000000
13     Sunday       Latte   35.000000

In [155]:
coffee_data.loc[[2,3],'Units Sold'] = np.nan

In [156]:
coffee_data[coffee_data['Units Sold'].isna()]

       Day Coffee Type  Units Sold
2  Tuesday    Espresso         NaN
3  Tuesday       Latte         NaN

In [157]:
coffee_data[coffee_data['Units Sold'].notna()]

          Day Coffee Type  Units Sold
0      Monday    Espresso        15.0
1      Monday       Latte        15.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

### Aggregating Data

In [160]:
bios_data[bios_data['born_country']== 'USA']['born_region'].value_counts().tail(20)

born_region
Vermont           68
Mississippi       66
Alabama           64
Kentucky          62
Tennessee         62
Nebraska          60
Rhode Island      56
Montana           55
South Carolina    50
Maine             50
Alaska            45
Arkansas          42
Idaho             41
New Mexico        38
Nevada            36
South Dakota      27
West Virginia     24
Delaware          22
North Dakota      16
Wyoming           14
Name: count, dtype: int64

In [163]:
coffee_data

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [166]:
coffee_new

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [167]:
coffee_new.groupby(['Coffee Type'])['Units Sold'].sum()

Coffee Type
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

In [168]:
coffee_new.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64

In [172]:
coffee_new.groupby(['Coffee Type','Day']).agg({'Units Sold':'sum','Price':'mean'})

                       Units Sold  Price
Coffee Type Day
Espresso    Friday             45   3.99
            Monday             25   3.99
            Saturday           45   3.99
            Sunday             45   3.99
            Thursday           40   3.99
            Tuesday            30   3.99
            Wednesday          35   3.99
Latte       Friday             35   5.99
            Monday             15   5.99
            Saturday           35   5.99
            Sunday             35   5.99
            Thursday           30   5.99
            Tuesday            20   5.99
            Wednesday          25   5.99

In [173]:
coffee_new

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [174]:
pivot_table = coffee_new.pivot(columns='Coffee Type',index='Day', values='Revenue')

In [179]:
pivot_table

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   89.85
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday        119.70  119.80
Wednesday      139.65  149.75

In [181]:
print(pivot_table.loc['Monday','Latte'])

89.85000000000001

In [183]:
pivot_table.sum(axis=1)

Day
Friday       389.2
Monday       189.6
Saturday     389.2
Sunday       389.2
Thursday     339.3
Tuesday      239.5
Wednesday    289.4
dtype: float64

In [184]:
bios_data

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

### Advance Functionality

In [196]:
coffee_new['yesterdayday_revenue'] = coffee_new['Revenue'].shift(2)

In [197]:
coffee_new

,Day,Coffee Type,Units Sold,Price,Revenue,yesterday_day,percentage_change,yesterdayday_revenue
0,Monday,Espresso,25,3.99,99.75,NaN,NaN,NaN
1,Monday,Latte,15,5.99,89.85,NaN,NaN,NaN
2,Tuesday,Espresso,30,3.99,119.70,99.75,1.200000,99.75
3,Tuesday,Latte,20,5.99,119.80,89.85,1.333333,89.85
4,Wednesday,Espresso,35,3.99,139.65,119.70,1.166667,119.70
5,Wednesday,Latte,25,5.99,149.75,119.80,1.250000,119.80
6,Thursday,Espresso,40,3.99,159.60,139.65,1.142857,139.65
7,Thursday,Latte,30,5.99,179.70,149.75,1.200000,149.75
8,Friday,Espresso,45,3.99,179.55,159.60,1.125000,159.60
9,Friday,Latte,35,5.99,209.65,179.70,1.166667,179.70
10,Saturday,Espresso,45,3.99,179.55,179.55,1.000000,179.55
11,Saturday,Latte,35,5.99,209.65,209.65,1.000000,209.65
12,Sunday,Espresso,45,3.99,179.55,179.55,1.000000,179.55
13,Sunday,Latte,35,5.99,209.65,209.65,1.000000,209.65

In [200]:
coffee_new['percentage_change'] = coffee_new['Revenue'] / coffee_new['yesterdayday_revenue'] * 100

In [201]:
coffee_new

,Day,Coffee Type,Units Sold,Price,Revenue,yesterday_day,percentage_change,yesterdayday_revenue
0,Monday,Espresso,25,3.99,99.75,NaN,NaN,NaN
1,Monday,Latte,15,5.99,89.85,NaN,NaN,NaN
2,Tuesday,Espresso,30,3.99,119.70,99.75,120.000000,99.75
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333,89.85
4,Wednesday,Espresso,35,3.99,139.65,119.70,116.666667,119.70
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000,119.80
6,Thursday,Espresso,40,3.99,159.60,139.65,114.285714,139.65
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000,149.75
8,Friday,Espresso,45,3.99,179.55,159.60,112.500000,159.60
9,Friday,Latte,35,5.99,209.65,179.70,116.666667,179.70
10,Saturday,Espresso,45,3.99,179.55,179.55,100.000000,179.55
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000,209.65
12,Sunday,Espresso,45,3.99,179.55,179.55,100.000000,179.55
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000,209.65

In [202]:
bios_data

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [ ]:
bios_data['height_rank'] = bios_data['height_cm'].rank(ascending=False)

In [212]:
bios_data.sort_values(['height_rank']).sample(10)[['name','height_rank']]

                     name  height_rank
20677      Jang Mi-Gyeong          NaN
143690      Nick Christie          NaN
138645    Tereza Hrochová          NaN
65027   Cláudio Bertolino      62600.5
140435      Natalie Raits          NaN
49446        Tomasz Rossa      46966.0
75307          Marco Rapp      38677.0
94355      Charles Burton      58380.5
70768       László Szalma       9882.0
67528        Henri Arnaud      66080.0

In [213]:
coffee_new.select_dtypes('float').cumsum().reset_index()

,index,Price,Revenue,yesterday_day,percentage_change,yesterdayday_revenue
0,0,3.99,99.75,NaN,NaN,NaN
1,1,9.98,189.60,NaN,NaN,NaN
2,2,13.97,309.30,99.75,120.000000,99.75
3,3,19.96,429.10,189.60,253.333333,189.60
4,4,23.95,568.75,309.30,370.000000,309.30
5,5,29.94,718.50,429.10,495.000000,429.10
6,6,33.93,878.10,568.75,609.285714,568.75
7,7,39.92,1057.80,718.50,729.285714,718.50
8,8,43.91,1237.35,878.10,841.785714,878.10
9,9,49.90,1447.00,1057.80,958.452381,1057.80
10,10,53.89,1626.55,1237.35,1058.452381,1237.35
11,11,59.88,1836.20,1447.00,1158.452381,1447.00
12,12,63.87,2015.75,1626.55,1258.452381,1626.55
13,13,69.86,2225.40,1836.20,1358.452381,1836.20

In [214]:
coffee_new['Cummulative_Revenue']=coffee_new['Revenue'].cumsum()

In [215]:
coffee_new

,Day,Coffee Type,Units Sold,Price,Revenue,yesterday_day,percentage_change,yesterdayday_revenue,Cummulative_Revenue
0,Monday,Espresso,25,3.99,99.75,NaN,NaN,NaN,99.75
1,Monday,Latte,15,5.99,89.85,NaN,NaN,NaN,189.60
2,Tuesday,Espresso,30,3.99,119.70,99.75,120.000000,99.75,309.30
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333,89.85,429.10
4,Wednesday,Espresso,35,3.99,139.65,119.70,116.666667,119.70,568.75
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000,119.80,718.50
6,Thursday,Espresso,40,3.99,159.60,139.65,114.285714,139.65,878.10
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000,149.75,1057.80
8,Friday,Espresso,45,3.99,179.55,159.60,112.500000,159.60,1237.35
9,Friday,Latte,35,5.99,209.65,179.70,116.666667,179.70,1447.00
10,Saturday,Espresso,45,3.99,179.55,179.55,100.000000,179.55,1626.55
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000,209.65,1836.20
12,Sunday,Espresso,45,3.99,179.55,179.55,100.000000,179.55,2015.75
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000,209.65,2225.40

In [217]:
latte=coffee_new[coffee_new['Coffee Type']== "Latte"].copy()
latte['3days']=latte['Units Sold'].rolling(3).mean()

In [218]:
latte

,Day,Coffee Type,Units Sold,Price,Revenue,yesterday_day,percentage_change,yesterdayday_revenue,Cummulative_Revenue,3days
1,Monday,Latte,15,5.99,89.85,NaN,NaN,NaN,189.6,NaN
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333,89.85,429.1,NaN
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000,119.80,718.5,20.000000
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000,149.75,1057.8,25.000000
9,Friday,Latte,35,5.99,209.65,179.70,116.666667,179.70,1447.0,30.000000
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000,209.65,1836.2,33.333333
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000,209.65,2225.4,35.000000